# Generated by Django 6.1.1 on 2026-09-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_symbol', models.CharField(max_length=20)),
                ('entry', models.DecimalField(decimal_places=2, max_digits=15)),
                ('exit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('entry_side', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('pnl', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
